### PR TITLE
server: handling ctrl-c signal

### LINKED ISSUE #483: server: handling ctrl-c signal
So that a ctrl-c signal from docker frontend can kill the process.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #483.

On the fly it supports addrs with any hostname.

Signed-off-by: tison <wander4096@gmail.com>

### CODE REVIEW

**Comment by huachaohuang** [comment]
Doesn't the current version simply quit on ctrl-c?

**Comment by tisonkun** [comment]
@huachaohuang if you run in host, ctrl-c kill the process. If you run with `docker`:

```bash
docker run --rm -it -p 21716:21716 ghcr.io/engula/engula server start
```

The process will ignore the signal.

cc @zheaoli do you have ideas why behaviors differ from envs?

**Comment by huachaohuang** [comment]
I think [this](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#trouble-signaling-pid-1) explains the problem. Simply speaking, the fallback signal handler will not be called when we are PID 1. So we need to handle the signal on our own in this case.

**Review by huachaohuang — APPROVED** [review]
LGTM, handling the signal seems no harm.

**Comment by Zheaoli** [comment]
I think it's good to handle the signal when we are PID 1, or we need a init process like tini or else instead.

**Pull request merged**
