### PR TITLE
makefile: intro makefile to simplify the local workflow

### PR DESCRIPTION
**Pull request by PsiACE**
Fixes: #150

add a basic makefile to simplify the local workflow

- make setup: setup all crates
- make lint: fmt check and clippy
- make audit: security audit and find unused deps
- make pre-commit: run all local workflow like ci

Signed-off-by: Chojan Shang <psiace@outlook.com>

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
If we'd like to add a pre-commit script, then let's directly do it, instead of adding a `Makefile` and assume how users will use it.

Also, it doesn't cover editor config checking and license auditing. I don't like to pull something random into the codebase before figuring out we really want it. If some developers need a handy script to verify a patch before submitting it, I suggest they write their own script and share it on the discussion forum. The difference here is that we don't maintain this script on behalf of the project, but leave it to developers unofficially.

**Comment by PsiACE** [comment]
> If we'd like to add a pre-commit script, then let's directly do it, instead of adding a Makefile and assume how users will use it.
This makefile also simplifies other commands.
> Also, it doesn't cover editor config checking and license auditing
We can add these checks. Databend also uses a makefile cmd to help format the shell and yaml.
> I don't like to pull something random into the codebase before figuring out we really want it. 
Nothing is really necessary. Just some sugar. In fact, experienced developers don't rely on this. But anyone would like to be able to take it easy.

**Comment by PsiACE** [comment]
@tisonkun convinced me that we should avoid introducing some unnecessary complexity. Unless we are faced with some tricky/complicated situation, there is no need to do anything redundant.

**Comment by huachaohuang** [comment]
@PsiACE @tisonkun Thanks for both of your work. I don't have a strong opinion about this, so I think we can keep it as it is until we have better ideas :)

**Pull request closed without merging**
