### PR TITLE
engula: add cmd to run a kernel server

### LINKED ISSUE #148: A grpc kernel that stores everything in a remote grpc kernel service
A grpc kernel integrates a grpc journal, storage, etc. It consists of a client and a server part. We need to provide a binary to start the kernel server.

### PR DESCRIPTION
**Pull request by PatrickNicholas**
This closes #148.

### CODE REVIEW

**Comment by PatrickNicholas** [comment]
There are alot of error transform codes in this PR. Shall we introduce some libraries (such as anyhow) to solve this problem?

**Review by huachaohuang — COMMENTED** [review]
Thanks. I can see that there are some dirty things here. So give me some time to refactor and come back to this later.

**Comment by tisonkun** [comment]
In this implementation, we can only launch all units on one node in a server. It may be OK for v0.2 but I think the goal is to have the flexibility to launch arbitrary units.

**Comment by PatrickNicholas** [comment]
> In this implementation, we can only launch all units on one node in a server. It may be OK for v0.2 but I think the goal is to have the flexibility to launch arbitrary units.

I the previous discussion: https://github.com/engula/engula/pull/171#issuecomment-988472342, we decided to serve version 2.0 first. Of course, our goal in the end must be to support launching arbitrary units.

**Comment by PatrickNicholas** [comment]
> So give me some time to refactor and come back to this later

@huachaohuang Is there any updates?

**Comment by huachaohuang** [comment]
> @huachaohuang Is there any updates?

I will come back to this in one or two days. Still working on other stuff.

**Comment by huachaohuang** [comment]
@PatrickNicholas Do you think we should close this in favor of #193 ?

**Comment by PatrickNicholas** [comment]
Now I close this because #193 is merged.

**Pull request closed without merging**
