### PR TITLE
Bump rust toolchain to `nightly-2022-06-08`

### PR DESCRIPTION
**Pull request by leiysky**

### CODE REVIEW

**Comment by tisonkun** [comment]
It seems new toolchain cause clippy complains :/

**Comment by leiysky** [comment]
https://github.com/tokio-rs/prost/issues/661

The issue got closed as soon as I was going to vote for it. So let's just disable the clippy for all the generated code.

**Review by tisonkun — APPROVED** [review]
LGTM. @huachaohuang I'm unsure your preference on toolchain bump. My opinion is that as long as we select a concrete version (instead of "nightly" which will auto update) and all tests pass, such version bump does no harm and potentially ease the burden of version upgrading when we really meet some features only available in a new version.

+1 to merge from my side.

**Review by huachaohuang — APPROVED** [review]
I'm OK with this if it works fine.

**Pull request merged**
