### PR TITLE
add outputs for example

### LINKED ISSUE #20: Example does not have output
Although it does do some works and write under `/tmp/engula_test/hello`, however, a user friendly message helps improve the journey.

For example, tell the user he/she can find the output under the directory or just list them out. It seems when failed, the framework itself can give error message.

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

This closes #20 .

### CODE REVIEW

**Comment by huachaohuang** [comment]
Hmm, I intend to show the example code in README to let those busy people glimpse how it works quickly.
The example shows how different components work together, so I think the code itself says more than any output.

**Comment by tisonkun** [comment]
> Hmm, I intend to show the example code in README to let those busy people glimpse how it works quickly.
> The example shows how different components work together, so I think the code itself says more than any output.

Sounds reasonable. We can keep the example in README while adding a few outputs ensuring the code works.

I know one can found the return code is `0` and guess it ends successfully, read the code and know how it works. However, there are others running first and then take a closer look, we can improve the experience with little effort.

**Review by huachaohuang — APPROVED** [review]
LGTM, the emoji looks fun :)

**Comment by tisonkun** [comment]
@huachaohuang seems clippy complains. Sorry for no verifying locally :(

**Comment by huachaohuang** [comment]
Never mind, I think it's enough for now.

**Pull request merged**
