### PR TITLE
docs: add a release guide

### LINKED ISSUE #205: Write a release guide
It will go to `docs/dev/release-guide.md`.

### PR DESCRIPTION
**Pull request by huachaohuang**
Closes #205 

Keep it simple for now.

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thanks for preparing this guide! Three comments here:

1. For publishing crates, I guess one should do a `cargo login`? Also push to main branch require permission. You may simply note the required permissions at the beginging.
2. Since the procedure is simple, I suggest not to define a `T` especially the definition isn't highlighted. You can take a look at [ReleasePrep](https://wiki.postgresql.org/wiki/ReleasePrep) and use "4-5 Days Before Release" alike description.
3. I notice that there's day of week sign "Monday", "Firday". Do you try to fix the day of week to make a release?

**Comment by tisonkun** [comment]
@huachaohuang thanks for your update. I'm curious why don't you use "Quote reply" but edit the original review comment. It mangles the display and doesn't send a notification to me.

**Comment by tisonkun** [comment]
> What's the difference between "4-5 Days Before Release" and "T-4d"?

From my experience, due to the definition of `T` isn't highlighted, a reader can confuse with what "T-4d" means. "4-5 Days Before Release" is self-explained, and we don't have to define such an abbr.

> Yeah, I am trying to make "Friday" the default option.

Good to know. Let me submit a pull request to this and manage content a bit.

**Comment by huachaohuang** [comment]
> @huachaohuang thanks for your update. I'm curious why don't you use "Quote reply" but edit the original review comment. It mangles the display and doesn't send a notification to me.

Oh, sorry about that, it must be a mistake 🤣

**Comment by huachaohuang** [comment]
@tisonkun Thanks for your PR, updated.

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@huachaohuang when squash and merge, you may retain/rewrite an expressive commit message and retain the "Signed-off-by:"/"Co-authored-by:" sections. It helps maintain a better commit history and track contributions.

**Pull request merged**
