### PR TITLE
journal: cleanup traits for v0.2

### PR DESCRIPTION
**Pull request by huachaohuang**
Check https://github.com/engula/engula/pull/143 for example usage of Journal.

### CODE REVIEW

**Comment by huachaohuang** [comment]
@tisonkun This also covers some parts of https://github.com/engula/engula/pull/139. Maybe you can help to fix the grpc journal implementation :)

**Comment by tisonkun** [comment]
If you're not in a hurry, I'll check it by the end of tomorrow.

**Comment by huachaohuang** [comment]
Sounds fine to me. I will work on Storage then.

**Review by tisonkun — COMMENTED** [review]
Generally looks good. To unblock further development, I can bring back the gRPC implement later after this PR merged.

Also, you can think of merging #139 first or just closing it as integrated into this PR.

Comments on this PR is that I should take more considerations on errors and the `ResultStream`. But it's OK to merge this PR now.

**Comment by tisonkun** [comment]
Also please try to avoid "force push". We can always use "squash and merge" later to clean up messy commits, but with a force push reviewers can hardly understand what's changed.

**Review by tisonkun — APPROVED** [review]
As #139 closed in favor of this one, +1 to merge.

I'll bring gRPC back based on this diff later. It seems besides the basic abstraction, errors and gRPC status should be considered a bit more. Also the result stream might be wrapped in gRPC implementation.

**Pull request merged**
