### PR TITLE
cargo: following Cargo toml conventions

### LINKED ISSUE #181: Consider following the Cargo.toml conventions
There is a Cargo.toml style guide [here](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/cargo.md). We can consider following it.

### PR DESCRIPTION
**Pull request by ygf11**
Resolves #181

### CODE REVIEW

**Comment by tisonkun** [comment]
@ygf11 I'd suggest you try to reach a consensus on the issue first instead of rushing into a pull request. BTW, is there a check to guard this change? Otherwise incoming patches can break this work easily.

**Comment by ygf11** [comment]
> I'd suggest you try to reach a consensus on the issue first instead of rushing into a pull request. BTW, is there a check to guard this change? Otherwise, incoming patches can break this work easily.

@tisonkun  Sure. Do we discuss here or in the issue?

**Comment by tisonkun** [comment]
Let's go back to the issue.

**Comment by huachaohuang** [comment]
According to https://github.com/engula/engula/issues/181, we should use a tool for this instead of doing it manually. @ygf11 Feel free to send another PR if you figure it out :)

**Pull request closed without merging**
