### PR TITLE
Remove some trait bounds that are not required

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Why do we original bring these bounds in fa69337e2179cbc15efd2dbf8a4b0a72cb5952cb?

Is it possible we share references of a journal or storage in a gRPC implementation? For example, hold a reference to the struct in different thread by different method call.

Anyway, we can add the bounds when needed.

**Review by zojw — APPROVED** [review]

**Comment by huachaohuang** [comment]
> Why do we original bring these bounds in [fa69337](https://github.com/engula/engula/commit/fa69337e2179cbc15efd2dbf8a4b0a72cb5952cb)?
> 
> Is it possible we share references of a journal or storage in a gRPC implementation? For example, hold a reference to the struct in different thread by different method call.
> 
> Anyway, we can add the bounds when needed.

Maybe some implementations need the trait bound, but not all of them. So I think we should let the specific implementation specify the trait bounds when necessary.

**Review by tisonkun — APPROVED** [review]
Thanks for your explanation @huachaohuang. LGTM.

It could reduce one round Q&A if more description provided :)

**Review by w41ter-l — APPROVED** [review]

**Comment by huachaohuang** [comment]
> FYI I'm trying to bring back gRPC journal to see if these trait bounds help.

I suggest that we leave the gRPC journal aside for now because the journal API is still unstable as described in #229 and #260.

**Comment by tisonkun** [comment]
@huachaohuang OK. I notice that I can test it on v0.2.0 and confirm that these trait bounds take effect for a gRPC implementation at that version. Possibly we will bring them back later.

And yes, "let the specific implementation specify the trait bounds when necessary", while if the Server takes a type parameter `T: Journal`, I'm afraid we will bring them back.

**Pull request merged**
